spring:
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


server:
  port : 8080
